package cn.kmbeast.Interceptor;

import cn.kmbeast.context.LocalThreadHolder;
import cn.kmbeast.pojo.api.ApiResult;
import cn.kmbeast.pojo.api.Result;
import cn.kmbeast.utils.JwtUtil;
import com.alibaba.fastjson2.JSONObject;
import io.jsonwebtoken.Claims;
import org.springframework.web.servlet.HandlerInterceptor;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.Writer;

/**
 *Token interceptor, used for request interception
 *Idea: After the user successfully logs in, they will receive a token generated by the backend, which will be stored locally by the frontend
 *Subsequent interface requests will include a token in the protocol header
 *All requests will be intercepted by the interceptor before execution: if the token verification passes, the request will be released normally, otherwise it will be returned directly
 */
public class JwtInterceptor implements HandlerInterceptor {

    /**
     * Pre interception
     *
     * @param request  current HTTP request
     * @param response current HTTP response
     * @param handler  chosen handler to execute, for type and/or instance evaluation
     * @return boolean true ： Release; False interception
     * @throws Exception Exception
     */
    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        String requestMethod = request.getMethod();
        //Release pre inspection request
        if ("OPTIONS".equals(requestMethod)) {
            return true;
        }
        String requestURI = request.getRequestURI();
        //Do not intercept login and error requests
        if (requestURI.contains("/login") || requestURI.contains("/error") || requestURI.contains("/file") || requestURI.contains("/register")) {
            return true;
        }
        String token = request.getHeader("token");
        Claims claims = JwtUtil.fromToken(token);
        //Failed to parse, return directly! There is no possibility of accessing subsequent resources！
        if (claims == null) {
            Result<String> error = ApiResult.error("Identity authentication exception, please log in first");
            response.setContentType("application/json;charset=UTF-8");
            Writer stream = response.getWriter();
            //Output failure information
            stream.write(JSONObject.toJSONString(error));
            stream.flush();
            stream.close();
            return false;
        }
        Integer userId = claims.get("id", Integer.class);
        Integer roleId = claims.get("role", Integer.class);
        //Place the parsed user ID and user role in LocalThread, making the current thread available
        LocalThreadHolder.setUserId(userId, roleId);
        return true;
    }
}
